# Generated by Django 5.1.3 on 2024-12-02 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdolPass', '0002_concert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='IdolPass.concert'),
        ),
    ]
