# Generated by Django 5.1.3 on 2024-12-03 12:31

import IdolPass.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdolPass', '0004_shoppingcart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tickets/', validators=[IdolPass.validators.validate_pdf_file]),
        ),
    ]
