# Generated by Django 5.1.3 on 2024-12-03 12:36

import IdolPass.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IdolPass', '0005_alter_ticket_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='concert_images/', validators=[IdolPass.validators.validate_image_file_extension]),
        ),
    ]
