# Generated by Django 5.1.3 on 2024-12-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IdolPass', '0006_alter_concert_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
